########################################
# Script: 07b_matched_random_modules_AD_batched.R
# Purpose: Run the final batched AD matched-random-module negative control.
# Input: Fixed modules, liver reference, AD matrices, phenotype data, and donor map.
# Output: AD empirical module and global negative-control results.
# Software: R
# Version: 4.5.2
# Random seed: 20260802; B=2000 per module
# Author: Study authors
########################################
options(stringsAsFactors=FALSE,width=180,contrasts=c("contr.treatment","contr.poly"))
suppressPackageStartupMessages({library(GSVA);library(lme4);library(metafor);library(ggplot2)})
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE);out<-file.path(root,"13_methodological_reanalysis_v9")
B<-as.integer(Sys.getenv("NEG_CONTROL_B","2000"));if(!is.finite(B)||B<1)stop("Invalid NEG_CONTROL_B")
seed<-20260802L;set.seed(seed);prefix<-if(B>=2000)""else paste0("benchmark_B",B,"_")
write_csv<-function(x,name)write.csv(x,file.path(out,paste0(prefix,name)),row.names=FALSE,na="")
z<-function(x)as.numeric(scale(x))
modules<-readRDS(file.path(root,"04_intermediate","gene_sets","liver_modules_combined.rds"));modules<-lapply(modules,function(x)unique(toupper(trimws(as.character(x)))))
ref<-readRDS(file.path(out,"preprocessed_main_old_mapping","liver_GSE135251.rds"));x483<-readRDS(file.path(out,"preprocessed_strict_mapping","AD_GSE48350.rds"));x330<-readRDS(file.path(out,"preprocessed_strict_mapping","AD_GSE33000.rds"))
universe<-Reduce(intersect,list(rownames(ref),rownames(x483),rownames(x330)));ref<-ref[universe,,drop=FALSE];x483<-x483[universe,,drop=FALSE];x330<-x330[universe,,drop=FALSE]
mean_ref<-rowMeans(ref);iqr_ref<-apply(ref,1,IQR);dec<-function(v)pmin(10L,pmax(1L,ceiling(rank(v,ties.method="average")/length(v)*10)));bin<-paste0("M",dec(mean_ref),"_V",dec(iqr_ref));names(bin)<-universe;pool<-split(universe,bin)

all_sets<-list();design_rows<-list()
for(m in names(modules)){
  g<-intersect(modules[[m]],universe);prof<-table(bin[g]);all_sets[[paste0(m,"__observed")]]<-g
  for(b in seq_len(B))all_sets[[paste0(m,"__null_",b)]]<-unlist(lapply(names(prof),function(k)sample(pool[[k]],as.integer(prof[[k]]),replace=FALSE)),use.names=FALSE)
  design_rows[[m]]<-data.frame(module=m,original_size=length(modules[[m]]),common_universe_size=length(g),coverage_fraction=length(g)/length(modules[[m]]),B=B,seed=seed,mean_decile_match=TRUE,IQR_decile_match=TRUE,target_detectability_match="common universe")
}
design<-do.call(rbind,design_rows);write_csv(design,"matched_random_module_design_table.csv")
score_sets<-function(expr){p<-GSVA::ssgseaParam(as.matrix(expr),all_sets,minSize=3,normalize=TRUE);as.matrix(GSVA::gsva(p,verbose=FALSE,BPPARAM=BiocParallel::SerialParam()))}
t0<-Sys.time();cat("Scoring",length(all_sets),"sets on GSE48350\n");s483<-score_sets(x483);cat("Scoring on GSE33000 after",as.numeric(difftime(Sys.time(),t0,units="mins")),"min\n");s330<-score_sets(x330);cat("Scoring complete after",as.numeric(difftime(Sys.time(),t0,units="mins")),"min\n")

mp<-read.csv(file.path(root,"08_donor_aware_reanalysis","02_GSE48350_donor_region_map.csv"),check.names=FALSE);mp<-mp[match(colnames(x483),mp$GSM),]
d483<-data.frame(diagnosis=factor(mp$diagnosis,levels=c("Control","AD")),region=factor(mp$region),age_z=z(mp$age),sex=factor(tolower(mp$sex)),donor_id=factor(mp$donor_id))
ph330<-readRDS(file.path(root,"04_intermediate","phenotype_tables","AD_GSE33000","pheno_harmonized.rds"));ph330<-ph330[match(colnames(x330),ph330$sample_id),];keep330<-ph330$diagnosis%in%c("AD","Control");s330<-s330[,keep330];ph330<-ph330[keep330,]
d330<-data.frame(diagnosis=factor(ph330$diagnosis,levels=c("Control","AD")),age_z=z(suppressWarnings(as.numeric(gsub("[^0-9.+-]","",ph330[["age:ch2"]])))),sex=factor(tolower(ph330[["gender:ch2"]])))

fit_lm_matrix<-function(scores,data){Y<-apply(scores,1,z);X<-model.matrix(~diagnosis+age_z+sex,data=data);inv<-solve(crossprod(X));bh<-inv%*%crossprod(X,Y);res<-Y-X%*%bh;df<-nrow(X)-ncol(X);sigma2<-colSums(res^2)/df;j<-match("diagnosisAD",colnames(X));se<-sqrt(inv[j,j]*sigma2);beta<-bh[j,];data.frame(beta=beta,SE=se,P=2*pt(-abs(beta/se),df=df))}
fit_lmer_refit<-function(scores,data){fit0<-lmer(z(scores[1,])~diagnosis+region+age_z+sex+(1|donor_id),data=data,REML=TRUE,control=lmerControl(optimizer="bobyqa",calc.derivs=FALSE));rows<-lapply(seq_len(nrow(scores)),function(i){fit<-if(i==1L)fit0 else suppressMessages(refit(fit0,newresp=z(scores[i,])));ss<-coef(summary(fit));b<-ss["diagnosisAD","Estimate"];se<-ss["diagnosisAD","Std. Error"];c(beta=b,SE=se,P=2*pnorm(-abs(b/se)),singular=isSingular(fit,tol=1e-5))});x<-as.data.frame(do.call(rbind,rows));x[]<-lapply(x,as.numeric);x}
reml_pair<-function(b1,se1,b2,se2){fit<-tryCatch(metafor::rma(yi=c(b1,b2),sei=c(se1,se2),method="REML"),error=function(e)NULL);if(is.null(fit))return(c(effect=NA,SE=NA,P=NA,tau2=NA,I2=NA));c(effect=as.numeric(fit$b),SE=fit$se,P=fit$pval,tau2=fit$tau2,I2=fit$I2)}

observed_rows<-list();null_rows<-list()
for(mi in seq_along(modules)){
  m<-names(modules)[mi];idx<-c(match(paste0(m,"__observed"),rownames(s483)),match(paste0(m,"__null_",seq_len(B)),rownames(s483)))
  e483<-fit_lmer_refit(s483[idx,,drop=FALSE],d483);e330<-fit_lm_matrix(s330[idx,,drop=FALSE],d330)
  meta<-t(vapply(seq_len(B+1L),function(i)reml_pair(e483$beta[i],e483$SE[i],e330$beta[i],e330$SE[i]),numeric(5)));colnames(meta)<-c("reml_effect","reml_SE","reml_P","tau2","I2")
  met<-data.frame(module=m,set_type=c("observed",rep("null",B)),replicate=c(0,seq_len(B)),beta_GSE48350=e483$beta,SE_GSE48350=e483$SE,P_GSE48350=e483$P,beta_GSE33000=e330$beta,SE_GSE33000=e330$SE,P_GSE33000=e330$P,meta)
  met$abs_beta_GSE48350<-abs(met$beta_GSE48350);met$abs_beta_GSE33000<-abs(met$beta_GSE33000);met$mean_abs_beta<-(met$abs_beta_GSE48350+met$abs_beta_GSE33000)/2;met$direction_consistent<-sign(met$beta_GSE48350)==sign(met$beta_GSE33000);met$cross_dataset_difference<-abs(met$beta_GSE48350-met$beta_GSE33000);met$dual_nominal_same_direction<-met$direction_consistent&met$P_GSE48350<.05&met$P_GSE33000<.05
  obs<-met[1,];nul<-met[-1,];ep_hi<-function(field)(1+sum(nul[[field]]>=obs[[field]],na.rm=TRUE))/(B+1);ep_lo<-function(field)(1+sum(nul[[field]]<=obs[[field]],na.rm=TRUE))/(B+1)
  dd<-design[design$module==m,]
  observed_rows[[m]]<-data.frame(module=m,original_size=dd$original_size,common_universe_size=dd$common_universe_size,coverage_fraction=dd$coverage_fraction,beta_GSE48350=obs$beta_GSE48350,SE_GSE48350=obs$SE_GSE48350,P_GSE48350=obs$P_GSE48350,beta_GSE33000=obs$beta_GSE33000,SE_GSE33000=obs$SE_GSE33000,P_GSE33000=obs$P_GSE33000,mean_abs_beta=obs$mean_abs_beta,empirical_P_mean_abs_beta=ep_hi("mean_abs_beta"),abs_beta_GSE48350=obs$abs_beta_GSE48350,empirical_P_abs_beta_GSE48350=ep_hi("abs_beta_GSE48350"),abs_beta_GSE33000=obs$abs_beta_GSE33000,empirical_P_abs_beta_GSE33000=ep_hi("abs_beta_GSE33000"),direction_consistent=obs$direction_consistent,empirical_P_direction_consistency=if(obs$direction_consistent)(1+sum(nul$direction_consistent))/(B+1)else 1,cross_dataset_difference=obs$cross_dataset_difference,empirical_P_cross_dataset_difference=ep_lo("cross_dataset_difference"),REML_effect=obs$reml_effect,REML_SE=obs$reml_SE,REML_P=obs$reml_P,empirical_P_abs_REML=(1+sum(abs(nul$reml_effect)>=abs(obs$reml_effect),na.rm=TRUE))/(B+1),dual_nominal_same_direction=obs$dual_nominal_same_direction,empirical_P_dual_nominal_same_direction=if(obs$dual_nominal_same_direction)(1+sum(nul$dual_nominal_same_direction))/(B+1)else 1,model_GSE48350="score_z ~ diagnosis + region + age_z + sex + (1 | donor_id)",model_GSE33000="score_z ~ diagnosis + age_z + sex",B=B,seed=seed)
  null_rows[[m]]<-nul[,c("module","replicate","mean_abs_beta","direction_consistent","cross_dataset_difference","dual_nominal_same_direction","reml_effect","abs_beta_GSE48350","abs_beta_GSE33000")]
  cat(sprintf("%02d/24 %s total elapsed %.1f min\n",mi,m,as.numeric(difftime(Sys.time(),t0,units="mins"))))
}
res<-do.call(rbind,observed_rows);null<-do.call(rbind,null_rows);emp_cols<-grep("^empirical_P_",names(res),value=TRUE);for(nm in emp_cols)res[[sub("empirical_P_","empirical_BH_FDR_",nm)]]<-p.adjust(res[[nm]],"BH")
write_csv(res,"matched_random_module_results_AD.csv");saveRDS(null,file.path(out,paste0(prefix,"matched_random_module_null_AD.rds")))
glob<-do.call(rbind,lapply(seq_len(B),function(b){d<-null[null$replicate==b,];data.frame(replicate=b,mean_abs_effect=mean(d$mean_abs_beta),direction_consistency_rate=mean(d$direction_consistent),mean_cross_dataset_difference=mean(d$cross_dataset_difference),dual_support_count=sum(d$dual_nominal_same_direction))}));og<-data.frame(mean_abs_effect=mean(res$mean_abs_beta),direction_consistency_rate=mean(res$direction_consistent),mean_cross_dataset_difference=mean(res$cross_dataset_difference),dual_support_count=sum(res$dual_nominal_same_direction))
gt<-data.frame(metric=c("mean_abs_effect","direction_consistency_rate","mean_cross_dataset_difference","dual_support_count"),observed=unlist(og[1,]),null_mean=c(mean(glob$mean_abs_effect),mean(glob$direction_consistency_rate),mean(glob$mean_cross_dataset_difference),mean(glob$dual_support_count)),null_q025=c(quantile(glob$mean_abs_effect,.025),quantile(glob$direction_consistency_rate,.025),quantile(glob$mean_cross_dataset_difference,.025),quantile(glob$dual_support_count,.025)),null_q975=c(quantile(glob$mean_abs_effect,.975),quantile(glob$direction_consistency_rate,.975),quantile(glob$mean_cross_dataset_difference,.975),quantile(glob$dual_support_count,.975)),tail=c("higher","higher","lower","higher"));gt$empirical_P<-c((1+sum(glob$mean_abs_effect>=og$mean_abs_effect))/(B+1),(1+sum(glob$direction_consistency_rate>=og$direction_consistency_rate))/(B+1),(1+sum(glob$mean_cross_dataset_difference<=og$mean_cross_dataset_difference))/(B+1),(1+sum(glob$dual_support_count>=og$dual_support_count))/(B+1));gt$BH_FDR<-p.adjust(gt$empirical_P,"BH");gt$analysis="AD common-universe matched random modules";write_csv(gt,"global_negative_control_tests.csv")
writeLines(c("# Matched random-module negative-control design","",paste0("Generated: ",format(Sys.time(),"%Y-%m-%d %H:%M:%S %z")),"",paste0("- Fixed seed: ",seed),paste0("- Random sets per real module: B=",B),paste0("- Common universe: ",length(universe)," genes measured in GSE135251, strict-mapped GSE48350 and strict-mapped GSE33000."),"- Exact matching: common-universe module size and joint GSE135251 mean-expression/IQR decile counts.","- GSVA/ssGSEA was applied jointly to all real and random sets; scores were standardized separately within each target dataset.","- GSE48350: `score_z ~ diagnosis + region + age_z + sex + (1 | donor_id)`; GSE33000: `score_z ~ diagnosis + age_z + sex`.","- Empirical P=(1+at-least-as-extreme null count)/(B+1); lower difference and higher magnitude/consistency/support are the stated one-sided tails.","- BH correction spans the 24 real modules separately for every empirical metric."),file.path(out,paste0(prefix,"matched_random_module_design.md")))
if(B>=2000){ord<-res$module[order(res$mean_abs_beta)];pd<-merge(null,res[,c("module","mean_abs_beta","cross_dataset_difference")],by="module",suffixes=c("_null","_observed"));pd$module<-factor(pd$module,levels=ord);p1<-ggplot(pd,aes(mean_abs_beta_null,module))+geom_violin(fill="#D8D8D8",color=NA,scale="width")+geom_point(data=res,aes(mean_abs_beta,module),inherit.aes=FALSE,color="#D24B40",size=1.2)+theme_classic(base_size=6.5,base_family="Arial")+labs(x="Mean absolute AD effect under matched null",y=NULL,title="Observed modules against matched random effects");p2<-ggplot(pd,aes(cross_dataset_difference_null,module))+geom_violin(fill="#D8D8D8",color=NA,scale="width")+geom_point(data=res,aes(cross_dataset_difference,module),inherit.aes=FALSE,color="#3182BD",size=1.2)+theme_classic(base_size=6.5,base_family="Arial")+labs(x="Absolute GSE48350-GSE33000 effect difference",y=NULL,title="Cross-dataset reproducibility under matched null");spl<-split(null$mean_abs_beta,null$module);sumd<-data.frame(module=res$module,observed=res$mean_abs_beta,null_median=vapply(spl,median,numeric(1))[res$module],null_low=vapply(spl,quantile,numeric(1),probs=.025)[res$module],null_high=vapply(spl,quantile,numeric(1),probs=.975)[res$module]);sumd$module<-factor(sumd$module,levels=ord);p3<-ggplot(sumd,aes(null_median,module))+geom_errorbar(aes(xmin=null_low,xmax=null_high),orientation="y",width=0,color="#767676")+geom_point(color="#767676",size=1)+geom_point(aes(x=observed),color="#D24B40",size=1.4)+theme_classic(base_size=6.5,base_family="Arial")+labs(x="Mean absolute effect: null median/95% interval and observed",y=NULL,title="Observed versus matched random modules");save<-function(p,stem){ggsave(file.path(out,paste0(stem,".pdf")),p,width=150/25.4,height=120/25.4,device=grDevices::cairo_pdf,family="Arial");ggsave(file.path(out,paste0(stem,".png")),p,width=150/25.4,height=120/25.4,dpi=600,device=ragg::agg_png)};save(p1,"Figure_random_null_AD_effects");save(p2,"Figure_random_null_reproducibility");save(p3,"Figure_observed_vs_random_modules")}
cat("Completed B=",B," in ",as.numeric(difftime(Sys.time(),t0,units="mins"))," minutes\n",sep="")
